const fs=require('fs'),path=require('path'),today=new Date().toISOString().slice(0,10),slug=today;
const feed=JSON.parse(fs.readFileSync(path.join(__dirname,'..','feed.json'),'utf8'));
if(feed.posts.find(p=>p.slug===slug)){console.log('Exists');process.exit(0)}
const articles=[
{title:'2026年最值得期待的10部电影：从国产大片到好莱坞巨制',tag:'电影推荐',intro:'今年片单比往年更丰富——国产科幻、动画崛起、好莱坞续集扎堆。帮你筛出最值得去电影院看的10部，省下踩雷的电影票钱。',sections:[{title:'🎬 国产片：科幻和动画扛大旗',body:'流浪地球3延续前作的高水准，郭帆导演的科幻美学已自成风格。哪吒2让国产动画再次刷新票房纪录。还有几部热度很高的国产黑马——不剧透，关注电影节获奖名单你就知道哪些值得期待。'},{title:'🌍 好莱坞：IP续集之年',body:'阿凡达4继续探索潘多拉星球的水世界。漫威DC各自重整旗鼓推出新英雄。经典IP续集扎堆——不是炒冷饭就是真正有诚意的续作，预告片就能看出端倪。判断标准：导演还是原来那个吗？换了导演的基本都是圈钱。'},{title:'📺 流媒体电影也在崛起',body:'Netflix和Apple TV+今年投入巨资制作原创电影，质量不输院线。卷福和汤姆汉克斯都有流媒体新片。在家里看大制作的感觉也很好——尤其是家里有投影仪的话。流媒体会员费比电影院便宜，只是少了爆米花的香气。'}]},
{title:'不刷短视频的时候可以做什么？比刷手机更有意思的7种消遣',tag:'生活方式',intro:'每天刷短视频2小时，一年就是730小时——等于整整一个月的时间消失了。不是让你完全不刷，而是给生活加点别的选择。当你有了更有意思的事情做，短视频自然就少了吸引力。',sections:[{title:'🎵 听一张完整的专辑',body:'不要听单曲推荐——听一张完整的专辑。从第一首听到最后一首，感受音乐人想表达的完整故事。推荐入门：周杰伦早期的任何一张、万能青年旅店的第一张、Pink Floyd的The Dark Side of the Moon。耳机戴上、手机放一边，给自己40分钟沉浸在完整的声音世界里。'},{title:'🎲 和朋友线下玩桌游',body:'不是狼人杀和三国杀——是德式桌游：卡卡颂、璀璨宝石、七大奇迹。规则简单但策略深，一局30-45分钟刚好。玩桌游的时候手机会被收走（因为要拿牌），自然地就脱离了屏幕。找三五个朋友周末聚一次，比在群聊里斗图有意思多了。'},{title:'📖 读一本不用动脑的小说',body:'不是成功学、不是工具书——是纯粹为了好看而读。悬疑推理让你想一口气读完、治愈小说让你在通勤路上找到慰藉、玄幻网文用来在床上打滚。读书最大的好处是专注——读进去的时候你完全不会想起还有手机这个东西。'},{title:'🎨 学一个纯粹为了快乐的小技能',body:'不是为了提升职场竞争力——单纯为了好玩。学魔术（在朋友面前变一个会很帅）、学折纸（日本折纸艺术很治愈）、学简单的吉他弹唱（三和弦能唱大部分歌）、学做一道精致的甜品（做完自己吃光）。这些小技能的共同点：动手、专注、有成果、不需要手机。'}]},
{title:'国产综艺越来越无趣？这5档良心综艺让你重拾看电视的快乐',tag:'综艺推荐',intro:'不是所有综艺都在尬笑和撕逼。还有一群人在认真做内容——有深度、有笑点、不尴尬、看完真的有收获。这些宝藏综艺可能流量不高但口碑炸裂。',sections:[{title:'📚 文化类综艺',body:'圆桌派：几个文化人围绕一个话题聊天，没有台本、没有任务、没有强制煽情。看了就知道什么叫\"有趣的灵魂\"。局部：陈丹青讲艺术，不是高高在上的学院派，是真正热爱艺术的人和你分享他觉得美的东西。典籍里的中国：把古籍变成戏剧，看完会想把这些书都翻出来读。'},{title:'😂 脱口秀和喜剧',body:'脱口秀大会每一季都在进步，从段子到深度。一年一度喜剧大赛让sketch喜剧在国内开始破圈——更短、更密集、更有创意。看喜剧最划算的地方：开心2小时，和看2小时手机后的感觉完全不同。'},{title:'🌍 旅行美食综艺',body:'早餐中国每集5分钟介绍一个城市的一家早餐店——看完会很想去那个城市走一趟。风味人间已经有纪录片级别的制作水准，陈晓卿能把一碗面拍出史诗感。这些不是综艺，是让你想走出去看世界的一扇窗。'}]},
{title:'音乐平台会员到底值不值？QQ音乐网易云Spotify对比',tag:'音乐消费',intro:'每个月花十几块听歌到底值不值？三款音乐App各有千秋——选对了每个月那十几块是最值的订阅支出。',sections:[{title:'🎧 QQ音乐：曲库最全',body:'周杰伦、五月天、陈奕迅——这些大牌歌手的版权都在QQ音乐手里。如果你听的以华语流行音乐为主，QQ音乐是最安全的选择。音质支持无损和杜比全景声。缺点：推荐算法不如竞品，界面有点花哨。学生会员只要8块/月。'},{title:'🌏 网易云音乐：社区感最强',body:'独立音乐人和民谣歌手的版权相对完整。网易云的核心资产是评论区——某些歌的评论比歌词还精彩。歌单推荐比QQ更懂你的口味。缺点：版权不完整，想听的歌经常灰掉。但如果你听独立/民谣/后摇这些小众类型，网易云是最好的选择。'},{title:'🎸 Spotify：全球体验最佳',body:'曲库最全（华语歌最近几年补得很齐了）、推荐算法最强（每周的Discover Weekly精准得吓人）、跨设备体验最好（电脑手机无缝切换）。缺点：没有歌词翻译、免费版有广告。Premium一个月十几块，如果90%的时间都在听音乐，这是最好的选择。'}]},
];
const idx=(new Date().getDate()-1)%articles.length,a=articles[idx];
feed.posts.unshift({slug,date:today,title:a.title,tag:a.tag,intro:a.intro,sections:a.sections});
feed.updated=today;fs.writeFileSync(path.join(__dirname,'..','feed.json'),JSON.stringify(feed,null,2));
const html=`<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>${a.title} - 文娱指南</title><style>*,*::before,*::after{margin:0;padding:0;box-sizing:border-box}:root{--bg:#fafafa;--card:#fff;--text:#1a1a2e;--t2:#555;--accent:#e11d48;--border:#e5e7eb;--r:12px}body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","Noto Sans SC",sans-serif;background:var(--bg);color:var(--text);line-height:1.9;font-size:16px}.container{max-width:750px;margin:0 auto;padding:0 20px}header{background:linear-gradient(135deg,#e11d48,#f43f5e);color:#fff;padding:36px 0;margin-bottom:24px}header a{color:rgba(255,255,255,.85);text-decoration:none;font-size:.9rem}header h1{font-size:1.5rem;margin-top:8px;line-height:1.4}.post{background:var(--card);border:1px solid var(--border);border-radius:var(--r);padding:32px}.post .intro{font-size:1rem;color:var(--t2);margin-bottom:28px;padding-bottom:20px;border-bottom:1px solid var(--border);line-height:1.8}.section{margin-bottom:24px}.section h3{font-size:1.05rem;margin-bottom:6px;color:var(--accent)}.section p{color:var(--t2);font-size:.92rem;line-height:1.9}footer{text-align:center;padding:24px;color:#999;font-size:.75rem}@media(max-width:600px){.post{padding:18px}}</style></head><body><header><div class="container"><a href="../index.html">← 首页</a><h1>${a.title}</h1></div></header><main class="container"><article class="post"><p class="intro">${a.intro}</p>${a.sections.map(s=>`<div class="section"><h3>${s.title}</h3><p>${s.body}</p></div>`).join('')}</article></main><footer><p>🎬 文娱指南 · 每日更新</p></footer></body></html>`;
fs.writeFileSync(path.join(__dirname,'..','posts',slug+'.html'),html);console.log('OK');
